version: "3.8"

services:
  # Dịch vụ Database (MySQL)
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pw
    networks:
      - wordpress_net

  # Dịch vụ WordPress
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "9876:80"
    volumes:
      - ./wordpress_src:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_pw
    networks:
      - wordpress_net

  # Dịch vụ phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8989:80"
    restart: always
    environment:
      PMA_HOST: db
    networks:
      - wordpress_net

volumes:
  db_data:
  wordpress_files:

networks:
  wordpress_net:
    driver: bridge
