version: "3.8"

services:
  wordpress:
    image: wordpress:6.6.1-php8.2-apache
    expose:
      - "80"
    volumes:
      - wordpress_files:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wordpress_net

volumes:
  wordpress_files:

networks:
  wordpress_net:
    driver: bridge
